import json
import os
import time
from pathlib import Path

import cloudinary.uploader
from fastapi.responses import JSONResponse

from server import VOICES, _request_audio  # loads .env + configures cloudinary

# Each voice speaks a greeting in its own language so the preview represents it
# properly. Keyed by the voice id's first char (Kokoro's language prefix):
# a/b = English, e = Spanish, f = French, h = Hindi, i = Italian, p = Portuguese.
SAMPLES = {
    "a": "Hi, this is a preview of my voice. Pick me to bring your words to life.",
    "b": "Hello, this is a preview of my voice. Pick me to bring your words to life.",
    "e": "Hola, esta es una muestra de mi voz. Elígeme para dar vida a tus palabras.",
    "f": "Bonjour, voici un aperçu de ma voix. Choisissez-moi pour donner vie à vos mots.",
    "h": "नमस्ते, यह मेरी आवाज़ का एक नमूना है। अपने शब्दों को जीवंत करने के लिए मुझे चुनें।",
    "i": "Ciao, questo è un esempio della mia voce. Scegli me per dare vita alle tue parole.",
    "p": "Olá, esta é uma amostra da minha voz. Escolha-me para dar vida às suas palavras.",
}

PREVIEW_FOLDER = "voice_previews"
OUT = Path(__file__).resolve().parent.parent / "frontend" / "src" / "lib" / "voicePreviews.ts"


def _upload_with_retry(path: str, vid: str, attempts: int = 3) -> str:
    """Upload a preview clip, retrying transient network drops (Cloudinary's
    upload host occasionally resets the connection mid-transfer)."""
    for attempt in range(1, attempts + 1):
        try:
            up = cloudinary.uploader.upload(
                path,
                resource_type="video",
                folder=PREVIEW_FOLDER,
                public_id=vid,
                overwrite=True,
            )
            return up["secure_url"]
        except Exception as exc:  # noqa: BLE001 — retry any transient upload error
            if attempt == attempts:
                raise
            print(f"  … upload retry {attempt}/{attempts - 1} for {vid}: {exc}", flush=True)
            time.sleep(2 * attempt)
    raise RuntimeError("unreachable")


def main() -> None:
    previews: dict[str, str] = {}
    total = len(VOICES)
    for i, v in enumerate(VOICES, 1):
        vid = v["id"]
        text = SAMPLES.get(vid[0], SAMPLES["a"])
        print(f"[{i}/{total}] {vid} …", flush=True)

        result = _request_audio("/generate", json={"voice": vid, "text": text, "speed": 1.0})
        if isinstance(result, JSONResponse):
            print(f"  ! skipped {vid}: model service error", flush=True)
            continue

        # One flaky voice must not sink the whole run — log it and move on.
        try:
            previews[vid] = _upload_with_retry(result, vid)
        except Exception as exc:  # noqa: BLE001
            print(f"  ! skipped {vid}: upload failed — {exc}", flush=True)
        finally:
            if result and os.path.exists(result):
                try:
                    os.remove(result)
                except OSError:
                    pass

    OUT.write_text(
        "// AUTO-GENERATED by backend/gen_previews.py — do not edit by hand.\n"
        "// voice id -> Cloudinary sample clip URL, played by the ▶ preview button.\n"
        "// Re-run the script to refresh after adding or changing voices.\n"
        f"export const VOICE_PREVIEWS: Record<string, string> = {json.dumps(previews, indent=2)};\n",
        encoding="utf-8",
    )
    print(f"\nWrote {len(previews)}/{total} previews -> {OUT}", flush=True)


if __name__ == "__main__":
    main()
